# Generated by Django 4.2.2 on 2023-12-07 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("creator", "0016_remove_consolidatedquestions_creator_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="consolidatedquestions",
            name="creator_request",
        ),
        migrations.RemoveField(
            model_name="creatoroutput",
            name="creator_request",
        ),
        migrations.RemoveField(
            model_name="creatorquestion",
            name="creator_question_category",
        ),
        migrations.RemoveField(
            model_name="creatorquestion",
            name="creator_question_type",
        ),
        migrations.RemoveField(
            model_name="creatorquestion",
            name="variable_type",
        ),
        migrations.AddField(
            model_name="consolidatedquestions",
            name="questoin_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="creator.creatorquestiongrouping",
            ),
        ),
        migrations.DeleteModel(
            name="CreatorRequest",
        ),
    ]
