# Generated by Django 4.2.2 on 2023-12-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("creator", "0018_alter_creatorquestion_internal_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creatorquestion",
            name="help_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
